### ISSUE TITLE
error uploading: HTTPSConnectionPool(host='api.segment.io', port=443)

### ISSUE THREAD

**Issue by LukGerman** [segmentio/analytics-python#142]
Sporadically I get this error: `error uploading: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:748)'),))` Please help.

analytics-python v1.2.9
requests v2.18.4
last occurrence: 11/Oct/2018 19:29:56 UTC

**Comment by nhi-nguyen** [comment]
Are you running OS X? There's a problem with some libraries needed by `requests` on OS X. `pip install pyopenssl ndg-httpsclient pyasn1 urllib3` seems to fix the problem for some people (https://github.com/requests/requests/issues/3006). Let us know if it applies to you.

**Comment by LukGerman** [comment]
I'm on a Ubuntu 16.04.1 and Python v3.6.2. I have also installed dependencies that you suggested. Because it happens sporadically I will test it for couple days and then will let you know if it's resolved or not. Thanks for quick response!

**Comment by kevinharvey** [comment]
I'm getting exactly the same sporadic behavior described by @LukGerman. 

analytics-python v1.2.9
requests v2.23.0
python 3.6.10

I'll try the same fix.

**Comment by nd4p90x** [comment]
This issue has been resolved in the latest versions, thank you.

**Comment by skumar-0105** [comment]
> ip install pyopenssl ndg-httpsclient pyasn1 urllib3

Thanks, the solution worked for me

**Comment by lalyndsighart** [comment]
Hello there, any help on this would be greatly appreciated.  I am getting this error when trying to install a package which I think uses the api.segment.io to track it's telemetry: 

error uploading: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

I have tried pip install pyopenssl ndg-httpsclient pyasn1 urllib3 but it doesn't work.  I am on a Windows 10 VM

**Comment by 96harsh56** [comment]
Hello there, i am facing this issue : - 

 DEBUG    rasa.telemetry  - Skipping telemetry reporting: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/track (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1091)')))

the reason for this SSL certificate expired but I have check and updated as well if there Is any issue.
currently, I am using rasa  2.0.2 version 
python 3.7.16

on mac os

**Comment by rippling-automerger** [comment]
Hi folks,
we are getting a similar issue with latest version (2.3.2).
If there is no connectivity, the client will output this:
```
HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113353550>: Failed to resolve 'api.segment.io' ([Errno 8] nodename nor servname provided, or not known)"))
```

in my case, I would like to hide these error messages to our users, as it could be confusing in case their is an application error, they would think it's related to segment.

Here is what I tried:
```py
    analytics.debug = False
    analytics.on_error = None
    analytics.log_handler = None

    logging.getLogger('requests').setLevel(logging.CRITICAL)
    logging.getLogger('urllib3').setLevel(logging.CRITICAL)

```

None of this work, these errors still show up.
It's actually easily reproduceable, so call `analytics.track()` when not connected to the internet.

Anybody else figured it out how to hide the output?

**Comment by RemyDeWolf** [comment]
Hi folks,
we are getting a similar issue with latest version (2.3.2).
If there is no connectivity, the client will output this:
```
HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113353550>: Failed to resolve 'api.segment.io' ([Errno 8] nodename nor servname provided, or not known)"))
```

in my case, I would like to hide these error messages to our users, as it could be confusing in case their is an application error, they would think it's related to segment.

Here is what I tried:
```py
    analytics.debug = False
    analytics.on_error = None
    analytics.log_handler = None

    logging.getLogger('requests').setLevel(logging.CRITICAL)
    logging.getLogger('urllib3').setLevel(logging.CRITICAL)

```

None of this work, these errors still show up.
It's actually easily reproduceable, so call `analytics.track()` when not connected to the internet.

Anybody else figured it out how to hide the output?
